name: Build Workflow

run-name: Build Workflow -- ${{github.head_ref || github.ref_name}}

on:
  push:
  workflow_dispatch:

jobs:
  build-job:
    name: Build Job
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
            distribution: 'zulu' # See 'Supported distributions' for available options
            java-version: '21'

      - name: Build Code
        run: mvn clean install






